# People on Banknotes

Whose faces appear on banknotes?

The file `people-on-banknotes.csv` contains data about individuals featured on banknotes from 38 countries. This dataset spans all 22 subregions and sub-subregions of the world, as defined by the United Nations Statistics Division's geoscheme.

It profiles 241 people, detailing their occupations and the year they first appeared on a banknote. Additionally, it includes their year of death — or `NaN` if they were still alive when the dataset was compiled.

Most banknotes were issued after the featured individual’s death. The column `first_death_diff` calculates the difference between the year of their first appearance on a banknote and their year of death (or remains `NaN` if the person was still living at the time of curation).

In [1]:
# FOR GOOGLE COLAB ONLY.
# Uncomment and run the code below. A dialog will appear to upload files.
# Upload 'people-on-banknotes.csv'.

# from google.colab import files
# uploaded = files.upload()

In [2]:
import pandas as pd

df = pd.read_csv('people-on-banknotes.csv')
df.head()

,country,currency,name,gender,occupation,value,first_appearance,death,first_death_diff,currency_code
0,Argentina,Argentine Peso,Eva Perón,F,Activist,100,2012,1952,60.0,ARS
1,Argentina,Argentine Peso,Julio Argentino Roca,M,Head of Gov't,100,1988,1914,74.0,ARS
2,Argentina,Argentine Peso,Domingo Faustino Sarmiento,M,Head of Gov't,50,1999,1888,111.0,ARS
3,Argentina,Argentine Peso,Juan Manuel de Rosas,M,Politician,20,1992,1877,115.0,ARS
4,Argentina,Argentine Peso,Manuel Belgrano,M,Founder,10,1970,1820,150.0,ARS

### Quick cleaning

The same person can appear on multiple banknotes. Below we drop the `value` column and remove duplicate people.

In [3]:
df = df.drop(columns=['value'])
df = df.drop_duplicates(subset="name")
df.head()

,country,currency,name,gender,occupation,first_appearance,death,first_death_diff,currency_code
0,Argentina,Argentine Peso,Eva Perón,F,Activist,2012,1952,60.0,ARS
1,Argentina,Argentine Peso,Julio Argentino Roca,M,Head of Gov't,1988,1914,74.0,ARS
2,Argentina,Argentine Peso,Domingo Faustino Sarmiento,M,Head of Gov't,1999,1888,111.0,ARS
3,Argentina,Argentine Peso,Juan Manuel de Rosas,M,Politician,1992,1877,115.0,ARS
4,Argentina,Argentine Peso,Manuel Belgrano,M,Founder,1970,1820,150.0,ARS

### Project Ideas

- What proportion of individuals featured are male versus female?
	- Hint: Use `value_counts(normalize=True)` to calculate percentages.

- Are writers or politicians more commonly depicted?

- What percentage of featured individuals are musicians?

- What percentage of banknotes were issued before the person’s death?
	- Hint: Look for negative values or NaN in `first_death_diff`.

- Who is the oldest historical figure in the dataset?

- Which countries feature the oldest historical figures on their banknotes?
	- Hint: Group by country and aggregate the year of death using the median. Sort the results.

- What percentage of individuals died at least 100 years before appearing on a banknote?

- Which individuals appeared on a banknote just one year after their death?

In [5]:
# What proportion of individuals featured are male versus female?
# Hint: Use value_counts(normalize=True) to calculate percentages.

df['gender'].value_counts(normalize=True)*100

M    78.008299
F    21.991701
Name: gender, dtype: float64

In [23]:
# Are writers or politicians more commonly depicted?
df['occupation'].value_counts()

df[df['occupation'].isin(['Writer', 'Politician'])]['occupation'].value_counts()

Writer        45
Politician    27
Name: occupation, dtype: int64

In [22]:
# What percentage of featured individuals are musicians?
(df["occupation"] == "Musician").mean()*100

4.979253112033195

In [31]:
# What percentage of banknotes were issued before the person’s death?
# Hint: Look for negative values or NaN in first_death_diff.

((df['first_death_diff']<0) | (df['first_death_diff'].isna())).mean()*100

4.564315352697095

In [42]:
df['death'] =pd.to_numeric(df['death'])

In [43]:
# Who is the oldest historical figure in the dataset?
df.loc[df['death'].idxmin()]

country                    Tunisia
currency            Tunisian Dinar
name                      Hannibal
gender                           M
occupation                Military
first_appearance              2013
death                       -183.0
first_death_diff            2196.0
currency_code                  TND
Name: 234, dtype: object

In [45]:
# Which countries feature the oldest historical figures on their banknotes?
# Hint: Group by country and aggregate the year of death using the median. Sort the results.
agg = df.groupby('country')['death'].median().sort_values()
agg

country
South Korea              1560.5
São Tomé and Príncipe    1779.5
Ukraine                  1817.5
United States            1826.0
Bolivia                  1839.5
Iceland                  1845.0
Venezuela                1849.5
Czech Republic           1869.0
Chile                    1879.0
Argentina                1888.0
Mexico                   1892.5
Japan                    1901.0
England                  1902.5
Dominican Republic       1905.0
Georgia                  1915.0
Serbia                   1927.0
Uruguay                  1931.0
Turkey                   1936.0
Australia                1936.5
Kyrgyzstan               1942.0
Tunisia                  1943.5
Canada                   1943.5
New Zealand              1943.5
Peru                     1945.0
Costa Rica               1947.0
Indonesia                1947.5
Colombia                 1948.0
Philippines              1948.0
Israel                   1956.5
Malawi                   1966.5
Jamaica                  1967.0
Bangladesh               1975.0
China                    1976.0
Nigeria                  1976.0
Sweden                   1996.0
Cape Verde               2010.0
South Africa             2013.0
Papua New Guinea         2021.0
Name: death, dtype: float64

In [48]:
# What percentage of individuals died at least 100 years before appearing on a banknote?

(df['first_death_diff']>=100).mean()*100

33.19502074688796

In [49]:
# Which individuals appeared on a banknote just one year after their death?
df[df['first_death_diff']==1]

,country,currency,name,gender,occupation,first_appearance,death,first_death_diff,currency_code
63,Colombia,Colombian Peso,Gabriel García Márquez,M,Writer,2015,2014.0,1.0,COP
173,Nigeria,Nigerian Naira,General Murtala Mohammed,M,Head of Gov't,1977,1976.0,1.0,NGN
190,Philippines,Philippine Piso,Corazon C. Aquino,F,Head of Gov't,2010,2009.0,1.0,PHP
191,Philippines,Philippine Piso,Manuel A. Roxas,M,Head of Gov't,1949,1948.0,1.0,PHP