# Volcano Eruptions

Which volcanoes have experienced the longest eruptions?

The dataset `volcanic-eruptions.csv` includes the start and end dates for all volcanic eruptions since 1800, along with each volcano's identification number. For eruptions that are still ongoing as of December 2024, the end date is recorded as December 2024.

This dataset excludes any eruptive pauses shorter than three months. If an eruption resumes after more than three months of inactivity, it is classified as a new eruption.

Note: Volcano Yasur in Vanuatu is not included in this list due to the absence of a clear start date.

In [44]:
# FOR GOOGLE COLAB ONLY.
# Uncomment and run the code below. A dialog will appear to upload files.
# Upload 'volcanic-eruptions.csv' and 'volcano-list.csv'.

# from google.colab import files
# uploaded = files.upload()

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

eruptions = pd.read_csv('volcanic-eruptions.csv')
eruptions.head(3)

   volcano_id start_date end_date
0      211020    07-1913  04-1944
1      211020    02-1864  11-1868
2      211020    12-1854  05-1855

### Additional dataset

The dataset `volcano-list.csv` provides detailed information about each volcano, including its name, country, latitude, longitude, and type.

In [2]:
volcanoes = pd.read_csv('volcano-list.csv')
volcanoes.head(3)

,volcano_id,volcano_name,country,volcanic_region_group,volcanic_region,volcano_landform,primary_volcano_type,activity_evidence,last_known_eruption,latitude,longitude,elevation_m,tectonic_setting,dominant_rock_type
0,210010,West Eifel Volcanic Field,Germany,European Volcanic Regions,Central European Volcanic Province,Cluster,Volcanic field,Eruption Dated,8300 BCE,50.170,6.850,600,Rift zone / Continental crust (>25 km),Foidite
1,210020,Chaine des Puys,France,European Volcanic Regions,Western European Volcanic Province,Cluster,Lava dome(s),Eruption Dated,4040 BCE,45.786,2.981,1464,Rift zone / Continental crust (>25 km),Basalt / Picro-Basalt
2,210030,Olot Volcanic Field,Spain,European Volcanic Regions,Western European Volcanic Province,Cluster,Volcanic field,Evidence Credible,Unknown,42.170,2.530,893,Intraplate / Continental crust (>25 km),Trachybasalt / Tephrite Basanite

### Project Ideas:

- Find the volcanoes that were erupting as of Dec 2024.

- Find the volcanoes that have had the longest volcanic eruptions. 

Hints:
- Use `pd.to_datetime`.

- Merge the volcanoes dataframe into eruptions.

- Before the merge, reduce the dataframes to the columns of interest.

- Use `df.sort_values`.

In [17]:
eruptions['start_date'] = pd.to_datetime(eruptions['start_date'])
eruptions['end_date'] = pd.to_datetime(eruptions['end_date'])
eruptions['duration'] = (eruptions['end_date'] - eruptions['start_date']).dt.days
eruptions[eruptions['duration'] ==eruptions['duration'].max()]

      volcano_id start_date   end_date  duration
2932      342030 1922-06-01 2024-12-01     37439

In [18]:
df = pd.merge(eruptions, volcanoes, on='volcano_id', how='left')

In [20]:
# longest eruptions
df[df['duration'] ==df['duration'].max()]

,volcano_id,start_date,end_date,duration,volcano_name,country,volcanic_region_group,volcanic_region,volcano_landform,primary_volcano_type,activity_evidence,last_known_eruption,latitude,longitude,elevation_m,tectonic_setting,dominant_rock_type
2932,342030,1922-06-01,2024-12-01,37439,Santa Maria,Guatemala,Middle America-Caribbean Volcanic Regions,Central America Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,14.757,-91.552,3745,Subduction zone / Continental crust (>25 km),Dacite

In [27]:
# Find the volcanoes that were erupting as of Dec 2024

df[df['start_date'].dt.month ==12]

,volcano_id,start_date,end_date,duration,volcano_name,country,volcanic_region_group,volcanic_region,volcano_landform,primary_volcano_type,activity_evidence,last_known_eruption,latitude,longitude,elevation_m,tectonic_setting,dominant_rock_type
2,211020,1854-12-01,1855-05-01,151,Vesuvius,Italy,European Volcanic Regions,Italian Peninsula Volcanic Provinces,Composite,Stratovolcano,Eruption Observed,1944 CE,40.8210,14.4260,1281,Subduction zone / Continental crust (>25 km),Phono-tephrite / Tephri-phonolite
3,211020,1855-12-01,1861-12-01,2192,Vesuvius,Italy,European Volcanic Regions,Italian Peninsula Volcanic Provinces,Composite,Stratovolcano,Eruption Observed,1944 CE,40.8210,14.4260,1281,Subduction zone / Continental crust (>25 km),Phono-tephrite / Tephri-phonolite
6,211020,1875-12-01,1906-04-01,11078,Vesuvius,Italy,European Volcanic Regions,Italian Peninsula Volcanic Provinces,Composite,Stratovolcano,Eruption Observed,1944 CE,40.8210,14.4260,1281,Subduction zone / Continental crust (>25 km),Phono-tephrite / Tephri-phonolite
8,211020,1870-12-01,1872-04-01,487,Vesuvius,Italy,European Volcanic Regions,Italian Peninsula Volcanic Provinces,Composite,Stratovolcano,Eruption Observed,1944 CE,40.8210,14.4260,1281,Subduction zone / Continental crust (>25 km),Phono-tephrite / Tephri-phonolite
24,211060,2001-12-01,2003-11-01,700,Etna,Italy,European Volcanic Regions,Sicily Volcanic Province,Composite,Stratovolcano(es),Eruption Observed,2024 CE,37.7480,14.9990,3357,Subduction zone / Continental crust (>25 km),Trachybasalt / Tephrite Basanite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3674,373080,1975-12-01,1975-12-01,0,Krafla,Iceland,Atlantic Ocean Volcanic Regions,Iceland Neovolcanic Rift Volcanic Province,Cluster,Caldera,Eruption Observed,1984 CE,65.7150,-16.7280,800,Rift zone / Oceanic crust (< 15 km),Basalt / Picro-Basalt
3680,373100,1867-12-01,1868-01-01,31,Tjornes Fracture Zone,Iceland,Atlantic Ocean Volcanic Regions,Arctic Ridge Volcanic Province,Cluster,Fissure vent,Eruption Observed,1868 CE,66.3090,-17.1180,-75,Rift zone / Oceanic crust (< 15 km),Basalt / Picro-Basalt
3708,390020,1972-12-01,2024-12-01,18993,Erebus,Antarctica,Antarctic-Scotia Volcanic Regions,McMurdo Volcanic Province,Composite,Stratovolcano,Eruption Observed,2024 CE,-77.5300,167.1700,3794,Intraplate / Continental crust (>25 km),Phonolite
3711,390030,1967-12-01,1967-12-01,0,Deception Island,Antarctica,Antarctic-Scotia Volcanic Regions,South Shetlands Volcanic Arc,Caldera,Caldera,Eruption Observed,1970 CE,-62.9567,-60.6367,602,Intraplate / Continental crust (>25 km),Basalt / Picro-Basalt
3715,390080,1936-12-01,1937-01-01,31,Bristol Island,United Kingdom,Antarctic-Scotia Volcanic Regions,South Sandwich Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2016 CE,-59.0170,-26.5330,1100,Subduction zone / Oceanic crust (< 15 km),Basalt / Picro-Basalt

In [29]:
df.sort_values(by='duration', ascending=False).head(1)

,volcano_id,start_date,end_date,duration,volcano_name,country,volcanic_region_group,volcanic_region,volcano_landform,primary_volcano_type,activity_evidence,last_known_eruption,latitude,longitude,elevation_m,tectonic_setting,dominant_rock_type
2932,342030,1922-06-01,2024-12-01,37439,Santa Maria,Guatemala,Middle America-Caribbean Volcanic Regions,Central America Volcanic Arc,Composite,Stratovolcano,Eruption Observed,2024 CE,14.757,-91.552,3745,Subduction zone / Continental crust (>25 km),Dacite