# Solar Eclipses

What is the average duration of total darkness during a total solar eclipse? When did the longest solar eclipse occur?

The file `solar-eclipses.csv` provides information on all solar eclipses from 1901 to 2100, leveraging the ability of scientists to accurately predict the timing and location of future eclipses.

A solar eclipse happens when the Moon moves between the Earth and the Sun, blocking the Sun's light either partially or completely. There are three primary types of solar eclipses:

1. Total Solar Eclipse: The Moon fully covers the Sun, casting a shadow on Earth and revealing the Sun's corona.

2. Partial Solar Eclipse: The Moon obscures only part of the Sun, creating a crescent-shaped appearance.

3. Annular Solar Eclipse: The Moon covers the center of the Sun, leaving a ring-like appearance, known as a "ring of fire," around the edges. This occurs when the Moon is too far from Earth to completely cover the Sun.

The `duration` variable indicates the length of time that the entire moon covers the sun.

In [290]:
# FOR GOOGLE COLAB ONLY.
# Uncomment and run the code below. A dialog will appear to upload files.
# Upload 'solar-eclipses.csv'.

# from google.colab import files
# uploaded = files.upload()

In [17]:
import pandas as pd
pd.set_option('display.max_colwidth', 1000)
df = pd.read_csv('solar-eclipses.csv')
df

,date,eclipse_type,magnitude,duration,region
0,05-18-1901,Total,1.068,06m29s,"s Asia, Australia, e Africa [Total: Indonesia, N Guinea, Madagascar]"
1,11-11-1901,Annular,0.922,11m01s,"ne Africa, Asia, w Europe [Annular: ne Africa, India, Sri Lanka, se Asia]"
2,04-08-1902,Partial,0.064,NaN,northern Canada
3,05-07-1902,Partial,0.859,NaN,"New Zealand, South Pacific"
4,10-31-1902,Partial,0.696,NaN,"c Asia, e Europe"
...,...,...,...,...,...
439,10-24-2098,Partial,0.006,NaN,Southern Ocean (near Antarctica)
440,03-21-2099,Annular,0.932,07m32s,"Australia, N.Z., Antarctica, N. America [Annular: Central Pacific]"
441,09-14-2099,Total,1.068,05m18s,"Americas, Africa [Total: Canada, U.S., Central Atlantic]"
442,03-10-2100,Annular,0.934,07m29s,"Australia, N. America [Annular: Central Pacific, U.S.]"
443,09-04-2100,Total,1.040,03m32s,"Africa, Antarctica [Total: Central Africa, Madagascar]"

### Project Ideas:

- When did the longest solar eclipse occur? The longest total eclipse?
	- Hint: convert duration to seconds. You can use `str.replace('s', '')` to remove the 's' from the duration values.

- What is the average duration of total solar eclipses? 

- Show the next 10 solar eclipses?
	- Hint: convert date to datetime.

In [18]:
def to_seconds(val):
    if pd.isna(val):
        return None
    val = val.replace('s', '')
    mins, secs = val.split('m')
    return int(mins)*60 + int(secs)

In [20]:
# YOUR CODE HERE (add additional cells as needed)
df['duration_secs'] = df['duration'].apply(to_seconds)
df.head()

,date,eclipse_type,magnitude,duration,region,duration_secs
0,05-18-1901,Total,1.068,06m29s,"s Asia, Australia, e Africa [Total: Indonesia, N Guinea, Madagascar]",389.0
1,11-11-1901,Annular,0.922,11m01s,"ne Africa, Asia, w Europe [Annular: ne Africa, India, Sri Lanka, se Asia]",661.0
2,04-08-1902,Partial,0.064,NaN,northern Canada,NaN
3,05-07-1902,Partial,0.859,NaN,"New Zealand, South Pacific",NaN
4,10-31-1902,Partial,0.696,NaN,"c Asia, e Europe",NaN

In [38]:
#  longest solar eclipse occur?

longest_overall_eclipse = df.loc[df['duration_secs'].idxmax()]
print(longest_overall_eclipse)

date                                                                                                                                  12-14-1955
eclipse_type                                                                                                                             Annular
magnitude                                                                                                                                  0.918
duration                                                                                                                                  12m09s
region           c & e Africa, Mid East, Asia, East Indies [Annular: Chad, Sudan, Ethiopia, Somalia, Myanmar, Thailand, Laos, Vietnam, se China]
duration_secs                                                                                                                              729.0
Name: 126, dtype: object

In [39]:
# longest total eclipse?
total_eclipses = df[df['eclipse_type']=='Total']
longest_total = total_eclipses.loc[total_eclipses['duration_secs'].idxmax()]
print(longest_total)

date                                                                                                                         06-20-1955
eclipse_type                                                                                                                      Total
magnitude                                                                                                                         1.078
duration                                                                                                                         07m08s
region           e Africa, e Asia, East Indies, n Australia [Total: Sri Lanka, Myanmar, Thailand, Laos, Cambodia, Vietnam, Philippines]
duration_secs                                                                                                                     428.0
Name: 125, dtype: object

In [43]:
# the average duration of total solar eclipses?
avg_total_eclipse = total_eclipses['duration_secs'].mean()
print(f'Average total eclipses ara - {avg_total_eclipse:.2f}')

Average total eclipses ara - 211.96

In [52]:
# Show the next 10 solar eclipses?

# to datetime 
df['date'] = pd.to_datetime(df['date'])

# get current date
today = pd.Timestamp.now()

next_10 =df[df['date']> today]
next_10[['date', 'eclipse_type','region']].head(10)

,date,eclipse_type,region
277,2026-08-12,Total,"n N. America, w Africa, Europe [Total: Arctic, Greenland, Iceland, Spain]"
278,2027-02-06,Annular,"S. America, Antarctica, w & s Africa [Annular: Chile, Argentina, Atlantic]"
279,2027-08-02,Total,"Africa, Europe, Mid East, w & s Asia [Total:Morocco, Spain, Algeria, Libya, Egypt, Saudi Arabia, Yemen, Somalia]"
280,2028-01-26,Annular,"e N. America, C. & S. America, w Europe, nw Africa [Annular: Ecuador, Peru, Brazil, Suriname, Spain, Portugal]"
281,2028-07-22,Total,"SE Asia, E. Indies, Australia, N.Z. [Total: Australia, N. Z.]"
282,2029-01-14,Partial,"N. America, C. America"
283,2029-06-12,Partial,"Arctic, Scandanavia, Alaska, n Asia, n Canada"
284,2029-07-11,Partial,"s Chile, s Argentina"
285,2029-12-05,Partial,"s Argentina, s Chile, Antarctica"
286,2030-06-01,Annular,"Europe, n Africa, Mid East, Asia, Arctic, Alaska [Annular: Algeria, Tunisia, Greece, Turkey, Russia, n. China, Japan]"

These are the upcoming eclipse occuration